### ISSUE TITLE
Not able to have mocked story and normal story

### ISSUE THREAD

**Issue by tychovbh** [nutboltu/storybook-addon-mock#111] opened 2022-05-30 07:03 UTC
I have a nextjs storybook project setup, with a laravel backend for authentication.

On every page I request the authenticated user: http://127.0.0.1:8000/api/user

This works perfect when I'm loggedin, but it is anyoning having to login everytime I start the project, so I mock the request. What also works perfect.

But my problem is, i'd like to have 2 stories:
1. Non mocked, so i can test the login flow
2. Mocked, so I can easily test the page i'm developing

So the strange thing, i have is the moment I import `withMock` my non mocked story doesn't work anymore, and the request above gets a 302 not found.

Here you can see the request works fine:
<img width="709" alt="Screenshot 2022-05-30 at 08 56 51" src="https://user-images.githubusercontent.com/5880561/170935372-de8419b4-2136-4405-b0b6-c3a98a38196e.png">

Now I add line:
`import withMock from 'storybook-addon-mock'`

And now the request breaks:
<img width="705" alt="Screenshot 2022-05-30 at 08 57 03" src="https://user-images.githubusercontent.com/5880561/170935516-c30e5459-bc05-4cce-8c4f-6b0ce4811cde.png">

Do you have any idea what this can be? I tried so many things, also in my backend API, but nothing helps.

**Comment by nutboltu** [comment] 2022-05-31 11:45
@tychovbh have you tried using the pause button to bypass mock data and use the actual api?
<img width="1460" alt="Screen Shot 2022-05-31 at 9 41 41 pm" src="https://user-images.githubusercontent.com/9896958/171165689-47eb29e4-8060-4d68-ae2e-45fec307363b.png">

**Comment by tychovbh** [comment] 2022-05-31 12:10
Hi @nutboltu thanks for the tip! But it seems I cannot disable this, because the story doesn't load properly because of the failed request:
<img width="1561" alt="Screenshot 2022-05-31 at 14 08 16" src="https://user-images.githubusercontent.com/5880561/171169748-b689282b-78b4-40a0-a165-4588080d39f7.png">

I can however switch to the mocked story, pause mock there, and then switch back to non mock story. This results in the same thing:

Mock story:
<img width="1785" alt="Screenshot 2022-05-31 at 14 08 33" src="https://user-images.githubusercontent.com/5880561/171169869-1b914a11-b0f3-4cbe-bef3-ba1a8c1811ce.png">

Switch back to non m
<img width="1788" alt="Screenshot 2022-05-31 at 14 08 44" src="https://user-images.githubusercontent.com/5880561/171169950-d5e0522f-3275-495c-9785-96521fa39796.png">
ock story:

**Comment by nutboltu** [comment] 2022-06-02 07:27
@tychovbh looking at the error, it appears the issue is from `Access-Control-Allow-Origin`. From your backend, you have to allow any origin. like (`Access-Control-Allow-Origin: '*'`). It's more like a backend configuration issue than FE.

**Comment by tychovbh** [comment] 2022-06-02 08:35
Looking at the headers helped, but it is actually not  a backend issue and also not cors related. I debugged the request in the API, and it is actually passing cors. The problem is that the moment I include this line:
`import withMock from 'storybook-addon-mock'`
All request headers are missing:

**Request without the withMock import**
<img width="629" alt="Screenshot 2022-06-02 at 10 20 56" src="https://user-images.githubusercontent.com/5880561/171588418-61ff3fa8-8ea9-4e14-9a53-4b8ad17e0909.png">
Backend has cookies:
<img width="479" alt="Screenshot 2022-06-02 at 10 27 42" src="https://user-images.githubusercontent.com/5880561/171588564-565898fa-4212-44eb-9186-60523a8460e6.png">


**Request with the withMock import**
<img width="482" alt="Screenshot 2022-06-02 at 10 21 23" src="https://user-images.githubusercontent.com/5880561/171588638-411e4222-d1e2-4f9c-9074-6662edd28e17.png">

Backend misses cookies:
<img width="348" alt="Screenshot 2022-06-02 at 10 26 54" src="https://user-images.githubusercontent.com/5880561/171588686-1c897b9b-9b70-47f5-ba4f-1a932f2dbeb3.png">


Does useMock always catch all outgoing requests, ands even though no mocking is set, it copies the request and sends it via another request api? And while doing that it is not including the cookies and other headers? I use axios with the `withCredentials` mode enabled, which is needed to automatically pass the auth cookies:
`const Client = axios.create({
    withCredentials: true
})
`

Is it possible to enable withCredentials in the mocking package through config? and all other headers?

I also now understand why the /api/user request has a 302 not found status and redirecting the request to /login. As you can see above the header `Accept: Application/json` is missing, when this header is missing Laravel treats the request as a non REST request.

**Comment by nutboltu** [comment] 2022-06-03 00:25
@tychovbh thanks for the confirmation. A new update with fix will come soon.

**Comment by nutboltu** [comment] 2022-06-03 04:52
@tychovbh The issue is fixed in [2.4.1](https://github.com/nutboltu/storybook-addon-mock/releases/tag/2.4.1)

**Closed** 2022-06-03 04:52 UTC
Labels: bug

**Comment by tychovbh** [comment] 2022-06-03 07:02
@nutboltu thanks a lot, i tested it and it works perfectly!
